### ISSUE TITLE
Wrong projection in output

### ISSUE THREAD

**Issue by ghtmtt** [zoran-cuckovic/QGIS-visibility-analysis#21]
Having both point and dtm layer in 32632 (metric), the output generated is placed in a wrong position (seems wrong output CRS).

Following picture with points and resulting layer:

![selection_134](https://user-images.githubusercontent.com/2884884/45020713-072b5800-b030-11e8-8c87-17221a9b15e0.png)

Following picture with points and dtm:

![selection_135](https://user-images.githubusercontent.com/2884884/45020766-2924da80-b030-11e8-84df-4e2ce1e70c06.png)

**Comment by zoran-cuckovic** [comment]
Hello,

The "Create viewpoints" routine is re-projecting points in case when they have different reference system than DEM. Note that you can override the ref system in QGIS, which may cause confusion if made by accident. 

Looking at your data it seems that the edge of the visibility field is oval in shape : this is a sign of an un-projected system (??)

I'm curious about this error - especially if it's due to lat/lon format. Perhaps you could upload a sample ?

**Comment by ghtmtt** [comment]
Hi, 

thanks for the reply. Actually both data are in the same CRS 32632. I made another test with other data and it works fine. 

I guess the issue can be closed, sorry for the noise ;)
