### ISSUE TITLE
Reverse viewshed

### ISSUE THREAD

**Issue by EvaK08** [zoran-cuckovic/QGIS-visibility-analysis#47]
Hello! I have question about Reverse viewshed. If I want to calculate it for different buildings with different height( from 15 to 40 m) do I need to put in OBSERVER HEIGHT value=5 m or this value can be calculated by formula: Building height-10 m or another formula?

**Comment by zoran-cuckovic** [comment]
Hello, 
If you need to know the visibility extent of a building, you should set the observer height to the building height (eg. 40 m) and the target height to observer eye level (eg. 1.7 m). If your buildings have varying heights,  you can store this information in a table field and use that field in the Create points routine. 
You may also need to subtract a value from the true building height in order to avoid overestimation, but that's a detail. 
See also on [https://landscapearchaeology.org/2020/viewshed-tutorial](https://landscapearchaeology.org/2020/viewshed-tutorial/)
