### ISSUE TITLE
Visibility Index: What does "Use height interpolation" mean and do?

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [zoran-cuckovic/QGIS-visibility-analysis#57]
First, thanx a lot for this crazy fast plugin! A coffee will soon be on it's way.
As I would like to use the Visibility index for a project, I need to be able to describe it's functionality for the documentation.
In the docs, I could not find any mentioning of the default option to use height interpolation.
So I kindly ask you to elaborate a bit on the why and how of the this option.
Cheers,
Bernd

**Comment by zoran-cuckovic** [comment]
Hello ! 
You can read on height interpolation here : [https://landscapearchaeology.org/2018/qgis-visibility-analysis-algorithm/](https://landscapearchaeology.org/2018/qgis-visibility-analysis-algorithm/). In a nutshell, lines of sight pass between pairs of pixels, an the terrain height is deduced (interpolated) by taking into account both values. Otherwise we can only check the nearest pixel, which is faster but less precise.
